export const Permission = {

  ASSIGN_ROLE: "ASSIGN_ROLE",
  REMOVE_ROLE: "REMOVE_ROLE",
  READ_USER_ROLES: "READ_USER_ROLES",
  MANAGE_USERS: "MANAGE_USERS",

  // ORGANIZATION
  READ_ORGANIZATION: "READ_ORGANIZATION",
  CREATE_ORGANIZATION: "CREATE_ORGANIZATION",
  UPDATE_ORGANIZATION: "UPDATE_ORGANIZATION",
  DELETE_ORGANIZATION: "DELETE_ORGANIZATION",

  //SUBSCRIPTION
  CREATE_SUBSCRIPTION: "CREATE_SUBSCRIPTION",
  READ_SUBSCRIPTION: "READ_SUBSCRIPTION",
  UPDATE_SUBSCRIPTION: "UPDATE_SUBSCRIPTION",
  DELETE_SUBSCRIPTION: "DELETE_SUBSCRIPTION",



  //AUDIT 
  READ_AUDIT: "READ_AUDIT",
  CREATE_AUDIT: "CREATE_AUDIT",
  UPDATE_AUDIT: "UPDATE_AUDIT",
  DELETE_AUDIT: "DELETE_AUDIT",



  // USER
  READ_USER: "READ_USER",
  CREATE_USER: "CREATE_USER",
  UPDATE_USER: "UPDATE_USER",
  DELETE_USER: "DELETE_USER",

  // FARM
  READ_FARM: "READ_FARM",
  CREATE_FARM: "CREATE_FARM",
  UPDATE_FARM: "UPDATE_FARM",
  DELETE_FARM: "DELETE_FARM",

  // LOT
  READ_LOT: "READ_LOT",
  CREATE_LOT: "CREATE_LOT",
  UPDATE_LOT: "UPDATE_LOT",
  DELETE_LOT: "DELETE_LOT",

  // ANIMAL
  READ_ANIMAL: "READ_ANIMAL",
  CREATE_ANIMAL: "CREATE_ANIMAL",
  UPDATE_ANIMAL: "UPDATE_ANIMAL",
  DELETE_ANIMAL: "DELETE_ANIMAL",

  // HEALTH / VETERINAIRE
  READ_HEALTH_RECORD: "READ_HEALTH_RECORD",
  CREATE_HEALTH_RECORD: "CREATE_HEALTH_RECORD",
  UPDATE_HEALTH_RECORD: "UPDATE_HEALTH_RECORD",
  DELETE_HEALTH_RECORD: "DELETE_HEALTH_RECORD",
  // TREATMENT 
  READ_TREATMENT: "READ_TREATMENT",
  CREATE_TREATMENT: "CREATE_TREATMENT",
  UPDATE_TREATMENT: "UPDATE_TREATMENT",
  DELETE_TREATMENT: "DELETE_TREATMENT",
  // VACCINATION
  READ_VACCINATION: "READ_VACCINATION",
  CREATE_VACCINATION: "CREATE_VACCINATION",
  UPDATE_VACCINATION: "UPDATE_VACCINATION",
  DELETE_VACCINATION: "DELETE_VACCINATION",


  // PRODUCTION
  READ_PRODUCTION: "READ_PRODUCTION",
  CREATE_PRODUCTION: "CREATE_PRODUCTION",
  UPDATE_PRODUCTION: "UPDATE_PRODUCTION",
  DELETE_PRODUCTION: "DELETE_PRODUCTION",

  // FEED
  READ_FEEDSTOCK: "READ_FEEDSTOCK",
  CREATE_FEEDSTOCK: "CREATE_FEEDSTOCK",
  UPDATE_FEEDSTOCK: "UPDATE_FEEDSTOCK",
  DELETE_FEEDSTOCK: "DELETE_FEEDSTOCK",

  // FEED PURCHASE
  DELETE_FEED_USAGE: "DELETE_FEED_USAGE",
  CREATE_FEED_USAGE: "CREATE_FEED_USAGE",
  UPDATE_FEED_USAGE: "UPDATE_FEED_USAGE",
  READ_FEED_USAGE: "READ_FEED_USAGE",

  // EQUIPMENT / MAINTENANCE
  READ_EQUIPMENT: "READ_EQUIPMENT",
  CREATE_EQUIPMENT: "CREATE_EQUIPMENT",
  UPDATE_EQUIPMENT: "UPDATE_EQUIPMENT",
  DELETE_EQUIPMENT: "DELETE_EQUIPMENT",
  READ_MAINTENANCE: "READ_MAINTENANCE",
  CREATE_MAINTENANCE: "CREATE_MAINTENANCE",
  UPDATE_MAINTENANCE: "UPDATE_MAINTENANCE",
  DELETE_MAINTENANCE: "DELETE_MAINTENANCE",

  // FINANCE
  READ_SALE: "READ_SALE",
  CREATE_SALE: "CREATE_SALE",
  UPDATE_SALE: "UPDATE_SALE",
  DELETE_SALE: "DELETE_SALE",

  READ_EXPENSE: "READ_EXPENSE",
  CREATE_EXPENSE: "CREATE_EXPENSE",
  UPDATE_EXPENSE: "UPDATE_EXPENSE",
  DELETE_EXPENSE: "DELETE_EXPENSE",

  READ_FINANCIAL_REPORT: "READ_FINANCIAL_REPORT",
  CREATE_FINANCIAL_REPORT: "CREATE_FINANCIAL_REPORT",
  UPDATE_FINANCIAL_REPORT: "UPDATE_FINANCIAL_REPORT",
  DELETE_FINANCIAL_REPORT: "DELETE_FINANCIAL_REPORT",

  READ_INVOICE: "READ_INVOICE",
  CREATE_INVOICE: "CREATE_INVOICE",
  UPDATE_INVOICE: "UPDATE_INVOICE",
  DELETE_INVOICE: "DELETE_INVOICE",

  // REPORTS / ALERTS / TASKS
  READ_REPORT: "READ_REPORT",
  CREATE_REPORT: "CREATE_REPORT",
  UPDATE_REPORT: "UPDATE_REPORT",
  DELETE_REPORT: "DELETE_REPORT",

  READ_ALERT: "READ_ALERT",
  CREATE_ALERT: "CREATE_ALERT",
  UPDATE_ALERT: "UPDATE_ALERT",
  DELETE_ALERT: "DELETE_ALERT",

  READ_FARMTASK: "READ_FARMTASK",
  CREATE_FARMTASK: "CREATE_FARMTASK",
  UPDATE_FARMTASK: "UPDATE_FARMTASK",
  DELETE_FARMTASK: "DELETE_FARMTASK",

  READ_AUDITLOG: "READ_AUDITLOG",
  CREATE_AUDITLOG: "CREATE_AUDITLOG",

  READ_PLAN: "READ_PLAN",
  CREATE_PLAN: "CREATE_PLAN",
  UPDATE_PLAN: "UPDATE_PLAN",
  DELETE_PLAN: "DELETE_PLAN",

  READ_BARN: "READ_BARN",
  CREATE_BARN: "CREATE_BARN",
  UPDATE_BARN: "UPDATE_BARN",
  DELETE_BARN: "DELETE_BARN",

  READ_HERD: "READ_HERD",
  CREATE_HERD: "CREATE_HERD",
  UPDATE_HERD: "UPDATE_HERD",
  DELETE_HERD: "DELETE_HERD",

  READ_BREED: "READ_BREED",
  CREATE_BREED: "CREATE_BREED",
  UPDATE_BREED: "UPDATE_BREED",
  DELETE_BREED: "DELETE_BREED",

  READ_SPECIES: "READ_SPECIES",
  CREATE_SPECIES: "CREATE_SPECIES",
  UPDATE_SPECIES: "UPDATE_SPECIES",
  DELETE_SPECIES: "DELETE_SPECIES",

  READ_PEN: "READ_PEN",
  CREATE_PEN: "CREATE_PEN",
  UPDATE_PEN: "UPDATE_PEN",
  DELETE_PEN: "DELETE_PEN",

  READ_ANIMAL_DEATH: "READ_ANIMAL_DEATH",
  CREATE_ANIMAL_DEATH: "CREATE_ANIMAL_DEATH",
  UPDATE_ANIMAL_DEATH: "UPDATE_ANIMAL_DEATH",
  DELETE_ANIMAL_DEATH: "DELETE_ANIMAL_DEATH",

  READ_TRANSFER: "READ_TRANSFER",
  CREATE_TRANSFER: "CREATE_TRANSFER",
  UPDATE_TRANSFER: "UPDATE_TRANSFER",
  DELETE_TRANSFER: "DELETE_TRANSFER",

  READ_WEIGHT: "READ_WEIGHT",
  CREATE_WEIGHT: "CREATE_WEIGHT",
  UPDATE_WEIGHT: "UPDATE_WEIGHT",
  DELETE_WEIGHT: "DELETE_WEIGHT",

  READ_MOVEMENT: "READ_MOVEMENT",
  CREATE_MOVEMENT: "CREATE_MOVEMENT",
  UPDATE_MOVEMENT: "UPDATE_MOVEMENT",
  DELETE_MOVEMENT: "DELETE_MOVEMENT",

  READ_PAYMENT: "READ_PAYMENT",
  CREATE_PAYMENT: "CREATE_PAYMENT",
  UPDATE_PAYMENT: "UPDATE_PAYMENT",
  DELETE_PAYMENT: "DELETE_PAYMENT",

  READ_PURCHASE: "READ_PURCHASE",
  CREATE_PURCHASE: "CREATE_PURCHASE",
  UPDATE_PURCHASE: "UPDATE_PURCHASE",
  DELETE_PURCHASE: "DELETE_PURCHASE",

  READ_BIRTH: "READ_BIRTH",
  CREATE_BIRTH: "CREATE_BIRTH",
  UPDATE_BIRTH: "UPDATE_BIRTH",
  DELETE_BIRTH: "DELETE_BIRTH",
  // REPRODUCTION
  READ_ANIMAL_REPRODUCTION: "READ_ANIMAL_REPRODUCTION",
  CREATE_ANIMAL_REPRODUCTION: "CREATE_ANIMAL_REPRODUCTION",
  UPDATE_ANIMAL_REPRODUCTION: "UPDATE_ANIMAL_REPRODUCTION",
  DELETE_ANIMAL_REPRODUCTION: "DELETE_ANIMAL_REPRODUCTION",

  //REPRODUCTION WITH BIRTH
  READ_REPRODUCTION_WITH_BIRTH: "READ_REPRODUCTION_WITH_BIRTH",
  CREATE_REPRODUCTION_WITH_BIRTH: "CREATE_REPRODUCTION_WITH_BIRTH",
  UPDATE_REPRODUCTION_WITH_BIRTH: "UPDATE_REPRODUCTION_WITH_BIRTH",
  DELETE_REPRODUCTION_WITH_BIRTH: "DELETE_REPRODUCTION_WITH_BIRTH",


  // PRODUCTION RECORD
  READ_PRODUCTION_RECORD: "READ_PRODUCTION_RECORD",
  CREATE_PRODUCTION_RECORD: "CREATE_PRODUCTION_RECORD",
  UPDATE_PRODUCTION_RECORD: "UPDATE_PRODUCTION_RECORD",
  DELETE_PRODUCTION_RECORD: "DELETE_PRODUCTION_RECORD",

  READ_ANIMAL_FEEDING: "READ_ANIMAL_FEEDING",
  CREATE_ANIMAL_FEEDING: "CREATE_ANIMAL_FEEDING",
  UPDATE_ANIMAL_FEEDING: "UPDATE_ANIMAL_FEEDING",
  DELETE_ANIMAL_FEEDING: "DELETE_ANIMAL_FEEDING",

  READ_REPRODUCTION: "READ_REPRODUCTION",
  CREATE_REPRODUCTION: "CREATE_REPRODUCTION",
  UPDATE_REPRODUCTION: "UPDATE_REPRODUCTION",
  DELETE_REPRODUCTION: "DELETE_REPRODUCTION",

  READ_EQUIPMENT_MAINTENANCE: "READ_EQUIPMENT_MAINTENANCE",
  CREATE_EQUIPMENT_MAINTENANCE: "CREATE_EQUIPMENT_MAINTENANCE",
  UPDATE_EQUIPMENT_MAINTENANCE: "UPDATE_EQUIPMENT_MAINTENANCE",
  DELETE_EQUIPMENT_MAINTENANCE: "DELETE_EQUIPMENT_MAINTENANCE",

  READ_INVENTORY: "READ_INVENTORY",
  CREATE_INVENTORY: "CREATE_INVENTORY",
  UPDATE_INVENTORY: "UPDATE_INVENTORY",
  DELETE_INVENTORY: "DELETE_INVENTORY",

  CREATE_SUPPLIER: "CREATE_SUPPLIER",
  READ_SUPPLIER: "READ_SUPPLIER",
  UPDATE_SUPPLIER: "UPDATE_SUPPLIER",
  DELETE_SUPPLIER: "DELETE_SUPPLIER",

  CREATE_FEED_PURCHASE: "CREATE_FEED_PURCHASE",
  READ_FEED_PURCHASE: "READ_FEED_PURCHASE",
  UPDATE_FEED_PURCHASE: "UPDATE_FEED_PURCHASE",
  DELETE_FEED_PURCHASE: "DELETE_FEED_PURCHASE",

  READ_SALE_ITEM: "READ_SALE_ITEM",
  CREATE_SALE_ITEM: "CREATE_SALE_ITEM",
  UPDATE_SALE_ITEM: "UPDATE_SALE_ITEM",
  DELETE_SALE_ITEM: "DELETE_SALE_ITEM",

  READ_EXPENSE_CATEGORY: "READ_EXPENSE_CATEGORY",
  CREATE_EXPENSE_CATEGORY: "CREATE_EXPENSE_CATEGORY",
  UPDATE_EXPENSE_CATEGORY: "UPDATE_EXPENSE_CATEGORY",
  DELETE_EXPENSE_CATEGORY: "DELETE_EXPENSE_CATEGORY",

  READ_NOTIFICATION: "READ_NOTIFICATION",
  CREATE_NOTIFICATION: "CREATE_NOTIFICATION",
  UPDATE_NOTIFICATION: "UPDATE_NOTIFICATION",
  DELETE_NOTIFICATION: "DELETE_NOTIFICATION",

  READ_FARM_TASK: "READ_FARM_TASK",
  CREATE_FARM_TASK: "CREATE_FARM_TASK",
  UPDATE_FARM_TASK: "UPDATE_FARM_TASK",
  DELETE_FARM_TASK: "DELETE_FARM_TASK",

  CREATE_FEED_SUPPLIER:"CREATE_FEED_SUPPLIER",
  READ_FEED_SUPPLIER:"READ_FEED_SUPPLIER",
  UPDATE_FEED_SUPPLIER:"UPDATE_FEED_SUPPLIER",
  DELETE_FEED_SUPPLIER:"DELETE_FEED_SUPPLIER",

  READ_API_KEY: "READ_API_KEY",
  CREATE_API_KEY: "CREATE_API_KEY",
  UPDATE_API_KEY: "UPDATE_API_KEY",
  DELETE_API_KEY: "DELETE_API_KEY",
} as const ;


export type PermissionCode = typeof Permission[keyof typeof Permission];

export function isPermissionCode(value: unknown): value is PermissionCode {
  return (
    typeof value === "string" &&
    Object.values(Permission).includes(value as PermissionCode)
  );
}