-- AlterTable
ALTER TABLE `animal` ADD COLUMN `barnId` INTEGER NULL,
    ADD COLUMN `herdId` INTEGER NULL,
    ADD COLUMN `penId` INTEGER NULL;

-- AddForeignKey
ALTER TABLE `Animal` ADD CONSTRAINT `Animal_barnId_fkey` FOREIGN KEY (`barnId`) REFERENCES `Barn`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Animal` ADD CONSTRAINT `Animal_penId_fkey` FOREIGN KEY (`penId`) REFERENCES `Pen`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Animal` ADD CONSTRAINT `Animal_herdId_fkey` FOREIGN KEY (`herdId`) REFERENCES `Herd`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
